// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: HW.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HWServiceClient is the client API for HWService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HWServiceClient interface {
	// Unary
	Hello(ctx context.Context, in *HWRequest, opts ...grpc.CallOption) (*HWResponse, error)
	// Server Streaming
	Hellooo(ctx context.Context, in *HWRequest, opts ...grpc.CallOption) (HWService_HelloooClient, error)
}

type hWServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHWServiceClient(cc grpc.ClientConnInterface) HWServiceClient {
	return &hWServiceClient{cc}
}

func (c *hWServiceClient) Hello(ctx context.Context, in *HWRequest, opts ...grpc.CallOption) (*HWResponse, error) {
	out := new(HWResponse)
	err := c.cc.Invoke(ctx, "/HelloWorld.HWService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hWServiceClient) Hellooo(ctx context.Context, in *HWRequest, opts ...grpc.CallOption) (HWService_HelloooClient, error) {
	stream, err := c.cc.NewStream(ctx, &HWService_ServiceDesc.Streams[0], "/HelloWorld.HWService/Hellooo", opts...)
	if err != nil {
		return nil, err
	}
	x := &hWServiceHelloooClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HWService_HelloooClient interface {
	Recv() (*HWResponse, error)
	grpc.ClientStream
}

type hWServiceHelloooClient struct {
	grpc.ClientStream
}

func (x *hWServiceHelloooClient) Recv() (*HWResponse, error) {
	m := new(HWResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HWServiceServer is the server API for HWService service.
// All implementations must embed UnimplementedHWServiceServer
// for forward compatibility
type HWServiceServer interface {
	// Unary
	Hello(context.Context, *HWRequest) (*HWResponse, error)
	// Server Streaming
	Hellooo(*HWRequest, HWService_HelloooServer) error
	mustEmbedUnimplementedHWServiceServer()
}

// UnimplementedHWServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHWServiceServer struct {
}

func (UnimplementedHWServiceServer) Hello(context.Context, *HWRequest) (*HWResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHWServiceServer) Hellooo(*HWRequest, HWService_HelloooServer) error {
	return status.Errorf(codes.Unimplemented, "method Hellooo not implemented")
}
func (UnimplementedHWServiceServer) mustEmbedUnimplementedHWServiceServer() {}

// UnsafeHWServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HWServiceServer will
// result in compilation errors.
type UnsafeHWServiceServer interface {
	mustEmbedUnimplementedHWServiceServer()
}

func RegisterHWServiceServer(s grpc.ServiceRegistrar, srv HWServiceServer) {
	s.RegisterService(&HWService_ServiceDesc, srv)
}

func _HWService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HWServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloWorld.HWService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HWServiceServer).Hello(ctx, req.(*HWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HWService_Hellooo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HWRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HWServiceServer).Hellooo(m, &hWServiceHelloooServer{stream})
}

type HWService_HelloooServer interface {
	Send(*HWResponse) error
	grpc.ServerStream
}

type hWServiceHelloooServer struct {
	grpc.ServerStream
}

func (x *hWServiceHelloooServer) Send(m *HWResponse) error {
	return x.ServerStream.SendMsg(m)
}

// HWService_ServiceDesc is the grpc.ServiceDesc for HWService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HWService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HelloWorld.HWService",
	HandlerType: (*HWServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HWService_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Hellooo",
			Handler:       _HWService_Hellooo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "HW.proto",
}
